openapi: "3.0.0"
info:
  title: T shirt store API
  description: API for t shirt store
  version: 1.1.0
servers:
  - url: "http://localhost:4000/api/{version}"
    description: Optional server description, e.g. Main (production) server
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: dummy route
          content:
            application/json:
              schema:
                type: array

  /signup:
    post:
      tags:
        - User
      summary: signup a new user. required files are - name, email, password and photo
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - photo
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                password:
                  type: string
                photo:
                  in: formData
                  description: The uploaded file data
                  type: file
                  format: binary
